# Generated by Django 4.1.4 on 2022-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store.custo_last_na_91d0f5_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store.customers',
        ),
    ]
