# Generated by Django 4.1.4 on 2022-12-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_last_name_customer_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
